config/routes.rb
Rails.application.routes.draw do


  resources :attendences
 root to: "subjects#index"
  get 'offlecture/index'
  get 'teacherdata/index'
	get 'timetable/table'
  get 'subjects/dashboard'

  resources :divisions
  resources :standards
  resources :timetables
  resources :subjects
  resources :teachers
  resources :teacherdata
  resources :offlecture

   get  :"/timetableapi", :to => "api#test"
   get  :"/subjectapi", :to => "api#testone"
   get  :"/teacherapi", :to => "api#testtwo"



   post :"/attendence", :to => "attend#create"
   post :"/ge", :to => "update#create" 
   post :"/go", :to => "update#create"
   post :"/subject", :to => "update#create"
   post :"/timetable", :to => "timetabel#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :standard
end

app/models/standard.rb
class Standard < ApplicationRecord

	has_many :divisions
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord

has_many :subjects
	
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	skip_before_action :verify_authenticity_token
	
	def test
		render :json => Timetable.all.as_json(:only => [:id, :lecture, :standard, :division, :subject, :teacher, :day])
		
	end
	
	def testone
		render :json => Subject.all.as_json(:only => [:id, :s_name, :teacher_id])
		
	end
	
	def testtwo
		render :json => Teacher.all.as_json(:only => [:id, :name, :qualification, :address, :mobile, :email])
		
	end
	
	def testtwo
		render :json => Teacher.all.as_json(:only => [:id, :name, :qualification, :address, :mobile, :email])
		
	end
end

app/controllers/attend_controller.rb
class AttendController < ApplicationController


	skip_before_action :verify_authenticity_token
	

def create
	  # byebug
    params[:data_value]
    @teacher= params[:data_value][:teacher]
    @day=params[:data_value][:day]
    @date=params[:data_value][:date]
    @time=params[:data_value][:time]
     @attenden=Attendence.where(teacher: @teacher,day: @day,date: @date,time: @time).ids.to_s.split("[")[1].split("]")[0].nil?
   		 Attendence.create(teacher: @teacher,day: @day,date: @date,time: @time)
	end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: [:show, :edit, :update, :destroy]

  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1
  # PATCH/PUT /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division.destroy
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: 'Division was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def division_params
      params.require(:division).permit(:division, :quantiy, :standard_id)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attend_helper.rb
module AttendHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/offlecture_helper.rb
module OfflectureHelper
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teacherdata_helper.rb
module TeacherdataHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/timetabel_helper.rb
module TimetabelHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/update_helper.rb
module UpdateHelper
end

app/views/divisions/_form.html.erb
<%= form_with(model: division, local: true) do |form| %>
  <% if division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% division.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :division %>
    <%= form.text_field :division %>
  </div>

  <div class="field">
    <%= form.label :quantiy %>
    <%= form.text_field :quantiy %>
  </div>

  <div class="field">
    <%= form.label :standard_id %>
     <%=form.collection_select(:standard_id , Standard.all, :id,:name, :include_blank => "select teacher") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Divisions</h1>

<table>
  <thead>
    <tr>
      <th>Division</th>
      <th>Quantiy</th>
      <th>Standard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @divisions.each do |division| %>
      <tr>
        <td><%= division.division %></td>
        <td><%= division.quantiy %></td>
        <td><%= division.standard %></td>
        <td><%= link_to 'Show', division %></td>
        <td><%= link_to 'Edit', edit_division_path(division) %></td>
        <td><%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>New Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Division:</strong>
  <%= @division.division %>
</p>

<p>
  <strong>Quantiy:</strong>
  <%= @division.quantiy %>
</p>

<p>
  <strong>Standard:</strong>
  <%= @division.standard %>
</p>

<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>