config/routes.rb
Rails.application.routes.draw do


  resources :attendences
 root to: "subjects#index"
  get 'offlecture/index'
  get 'teacherdata/index'
	get 'timetable/table'
  get 'subjects/dashboard'

  resources :divisions
  resources :standards
  resources :timetables
  resources :subjects
  resources :teachers
  resources :teacherdata
  resources :offlecture

   get  :"/timetableapi", :to => "api#test"
   get  :"/subjectapi", :to => "api#testone"
   get  :"/teacherapi", :to => "api#testtwo"



   post :"/attendence", :to => "attend#create"
   post :"/ge", :to => "update#create" 
   post :"/go", :to => "update#create"
   post :"/subject", :to => "update#create"
   post :"/timetable", :to => "timetabel#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :standard
end

app/models/standard.rb
class Standard < ApplicationRecord

	has_many :divisions
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord

has_many :subjects
	
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	skip_before_action :verify_authenticity_token
	
	def test
		render :json => Timetable.all.as_json(:only => [:id, :lecture, :standard, :division, :subject, :teacher, :day])
		
	end
	
	def testone
		render :json => Subject.all.as_json(:only => [:id, :s_name, :teacher_id])
		
	end
	
	def testtwo
		render :json => Teacher.all.as_json(:only => [:id, :name, :qualification, :address, :mobile, :email])
		
	end
	
	def testtwo
		render :json => Teacher.all.as_json(:only => [:id, :name, :qualification, :address, :mobile, :email])
		
	end
end

app/controllers/attend_controller.rb
class AttendController < ApplicationController


	skip_before_action :verify_authenticity_token
	

def create
	  # byebug
    params[:data_value]
    @teacher= params[:data_value][:teacher]
    @day=params[:data_value][:day]
    @date=params[:data_value][:date]
    @time=params[:data_value][:time]
     @attenden=Attendence.where(teacher: @teacher,day: @day,date: @date,time: @time).ids.to_s.split("[")[1].split("]")[0].nil?
   		 Attendence.create(teacher: @teacher,day: @day,date: @date,time: @time)
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :qualification, :address, :mobile, :email)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attend_helper.rb
module AttendHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/offlecture_helper.rb
module OfflectureHelper
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teacherdata_helper.rb
module TeacherdataHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/timetabel_helper.rb
module TimetabelHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/update_helper.rb
module UpdateHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :qualification %>
    <%= form.text_field :qualification %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Qualification</th>
      <th>Address</th>
      <th>Mobile</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.id %></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.qualification %></td>
        <td><%= teacher.address %></td>
        <td><%= teacher.mobile %></td>
        <td><%= teacher.email %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @teacher.qualification %>
</p>

<p>
  <strong>Address:</strong>
  <%= @teacher.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @teacher.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>