config/routes.rb
Rails.application.routes.draw do


  resources :attendences
 root to: "subjects#index"
  get 'offlecture/index'
  get 'teacherdata/index'
	get 'timetable/table'
  get 'subjects/dashboard'

  resources :divisions
  resources :standards
  resources :timetables
  resources :subjects
  resources :teachers
  resources :teacherdata
  resources :offlecture

   get  :"/timetableapi", :to => "api#test"
   get  :"/subjectapi", :to => "api#testone"
   get  :"/teacherapi", :to => "api#testtwo"



   post :"/attendence", :to => "attend#create"
   post :"/ge", :to => "update#create" 
   post :"/go", :to => "update#create"
   post :"/subject", :to => "update#create"
   post :"/timetable", :to => "timetabel#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :standard
end

app/models/standard.rb
class Standard < ApplicationRecord

	has_many :divisions
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord

has_many :subjects
	
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	skip_before_action :verify_authenticity_token
	
	def test
		render :json => Timetable.all.as_json(:only => [:id, :lecture, :standard, :division, :subject, :teacher, :day])
		
	end
	
	def testone
		render :json => Subject.all.as_json(:only => [:id, :s_name, :teacher_id])
		
	end
	
	def testtwo
		render :json => Teacher.all.as_json(:only => [:id, :name, :qualification, :address, :mobile, :email])
		
	end
	
	def testtwo
		render :json => Teacher.all.as_json(:only => [:id, :name, :qualification, :address, :mobile, :email])
		
	end
end

app/controllers/attend_controller.rb
class AttendController < ApplicationController


	skip_before_action :verify_authenticity_token
	

def create
	  # byebug
    params[:data_value]
    @teacher= params[:data_value][:teacher]
    @day=params[:data_value][:day]
    @date=params[:data_value][:date]
    @time=params[:data_value][:time]
     @attenden=Attendence.where(teacher: @teacher,day: @day,date: @date,time: @time).ids.to_s.split("[")[1].split("]")[0].nil?
   		 Attendence.create(teacher: @teacher,day: @day,date: @date,time: @time)
	end
end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController
  before_action :set_standard, only: [:show, :edit, :update, :destroy]

  # GET /standards
  # GET /standards.json
  def index
    @standards = Standard.all
  end

  # GET /standards/1
  # GET /standards/1.json
  def show
  end

  # GET /standards/new
  def new
    @standard = Standard.new
  end

  # GET /standards/1/edit
  def edit
  end

  # POST /standards
  # POST /standards.json
  def create
    @standard = Standard.new(standard_params)

    respond_to do |format|
      if @standard.save
        format.html { redirect_to @standard, notice: 'Standard was successfully created.' }
        format.json { render :show, status: :created, location: @standard }
      else
        format.html { render :new }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standards/1
  # PATCH/PUT /standards/1.json
  def update
    respond_to do |format|
      if @standard.update(standard_params)
        format.html { redirect_to @standard, notice: 'Standard was successfully updated.' }
        format.json { render :show, status: :ok, location: @standard }
      else
        format.html { render :edit }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standards/1
  # DELETE /standards/1.json
  def destroy
    @standard.destroy
    respond_to do |format|
      format.html { redirect_to standards_url, notice: 'Standard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standard
      @standard = Standard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def standard_params
      params.require(:standard).permit(:name)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attend_helper.rb
module AttendHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/offlecture_helper.rb
module OfflectureHelper
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teacherdata_helper.rb
module TeacherdataHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/timetabel_helper.rb
module TimetabelHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/update_helper.rb
module UpdateHelper
end

app/views/standards/_form.html.erb
<%= form_with(model: standard, local: true) do |form| %>
  <% if standard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(standard.errors.count, "error") %> prohibited this standard from being saved:</h2>

      <ul>
      <% standard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/standards/edit.html.erb
<h1>Editing Standard</h1>

<%= render 'form', standard: @standard %>

<%= link_to 'Show', @standard %> |
<%= link_to 'Back', standards_path %>

app/views/standards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Standards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @standards.each do |standard| %>
      <tr>
        <td><%= standard.name %></td>
        <td><%= link_to 'Show', standard %></td>
        <td><%= link_to 'Edit', edit_standard_path(standard) %></td>
        <td><%= link_to 'Destroy', standard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Standard', new_standard_path %>

app/views/standards/new.html.erb
<h1>New Standard</h1>

<%= render 'form', standard: @standard %>

<%= link_to 'Back', standards_path %>

app/views/standards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @standard.name %>
</p>

<%= link_to 'Edit', edit_standard_path(@standard) %> |
<%= link_to 'Back', standards_path %>